spring.application.name=ItauJava10x
spring.output.ansi.enabled=ALWAYS

transacoes.estatisticas.segundos=60


# Tradução: log.nível.seu-pacote = DEPURAÇÃO - liga o DEBUG apenas para o que está dentro de IgauJava10x
logging.level.tech.gtech.ItauJava10x=DEBUG

# ligaria o log DEBUG para toda a aplicação - incluindo o Spring
# logging.level.root=DEBUG